import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { GrokAcpServer, type Session } from "./server.js";
import { bindExecutionCapability } from "./executionCapability.js";

const profile = { status:"available" as const, platform:"win32", osFamily:"windows" as const, executable:process.env.ComSpec ?? "C:\\Windows\\System32\\cmd.exe", argvPrefix:["/d","/s","/c"] as const, displayName:"Command Prompt (cmd.exe)", dialect:"cmd" as const, pathSeparator:"\\" as const, syntax:{quoting:"",chaining:"",redirection:""} };
function call(name:string, args:Record<string,unknown>, id=name): any { return { id, type:"function", function:{name, arguments:JSON.stringify(args)} }; }
function harness(root:string, env:Record<string,string> = {}, decision:"deny"|"allow_once" = "deny") {
  const server = new GrokAcpServer(); const events:any[]=[]; let permissions=0;
  (server as any).notify = (type:string, params:any) => events.push({type,params});
  (server as any).waitPermission = async () => { permissions += 1; return decision; };
  const session: Session = { id:"s", messages:[], pendingEdits:new Map(), sessionWrite:false, sessionShell:false, capability:bindExecutionCapability(profile,root,env) };
  return {server,session,events,get permissions(){return permissions;}};
}
test("structured repository tools execute without permission events", async () => { const root=await fs.mkdtemp(path.join(os.tmpdir(),"grok-bnd-")); try { await fs.writeFile(path.join(root,"a.txt"),"needle"); const h=harness(root); for (const [name,args] of [["list_dir",{path:"."}],["read_file",{path:"a.txt"}],["grep",{pattern:"needle",path:"."}] ] as const) await h.server.executeTool(h.session,call(name,args)); assert.equal(h.permissions,0); assert.equal(h.events.filter(e=>e.type==="tool_run"&&e.params.lifecycle==="terminal").length,3); } finally { await fs.rm(root,{recursive:true,force:true}); } });
test("exact ls is rejected before permission and unavailable has no process", async()=>{ const root=await fs.mkdtemp(path.join(os.tmpdir(),"grok-bnd-")); try { const h=harness(root,{Path:"",PATHEXT:".EXE"}); const out=await h.server.executeTool(h.session,call("run_shell",{command:"ls"})); const terminal=h.events.find(e=>e.type==="tool_run"&&e.params.lifecycle==="terminal"); assert.equal(h.permissions,0); assert.equal(terminal.params.execution,"not_executed"); assert.equal(terminal.params.reasonCode,"leading_command_unresolved"); assert.match(out,/not_executed/); } finally { await fs.rm(root,{recursive:true,force:true}); } });
test("unavailable capability rejects without permission", async()=>{ const root=await fs.mkdtemp(path.join(os.tmpdir(),"grok-bnd-")); try { const h=harness(root); h.session.capability=bindExecutionCapability({status:"unavailable",platform:"plan9",osFamily:"unsupported",executable:null,argvPrefix:[],displayName:null,dialect:null,pathSeparator:"/",syntax:null,reasonCode:"unsupported_platform",reason:"Unsupported host platform"},root,{}); await h.server.executeTool(h.session,call("run_shell",{command:"echo ok"})); const terminal=h.events.find(e=>e.type==="tool_run"&&e.params.lifecycle==="terminal"); assert.equal(h.permissions,0); assert.equal(terminal.params.reasonCode,"unsupported_platform"); assert.equal(terminal.params.execution,"not_executed"); } finally { await fs.rm(root,{recursive:true,force:true}); } });
test("uncertain shell reaches deny permission and executed failure remains failed", async()=>{ const root=await fs.mkdtemp(path.join(os.tmpdir(),"grok-bnd-")); try { const h=harness(root,{Path:"",PATHEXT:".EXE"}); await h.server.executeTool(h.session,call("run_shell",{command:"echo %CD%"},"u")); assert.equal(h.permissions,1); h.session.sessionShell=true; const fail=await h.server.executeTool(h.session,call("run_shell",{command:"exit /b 7"},"f")); const terminal=h.events.filter(e=>e.type==="tool_run"&&e.params.toolCallId==="f").at(-1); assert.equal(terminal.params.execution,"executed"); assert.equal(terminal.params.status,"failed"); assert.match(fail,/exit_code/); } finally { await fs.rm(root,{recursive:true,force:true}); } });
test("approved compatible command asks once and uses workspace cwd", async()=>{ const root=await fs.mkdtemp(path.join(os.tmpdir(),"grok-bnd-")); try { const h=harness(root,{Path:"",PATHEXT:".EXE"},"allow_once"); const out=await h.server.executeTool(h.session,call("run_shell",{command:"echo %CD%"},"ok")); assert.equal(h.permissions,1); const terminal=h.events.filter(e=>e.type==="tool_run"&&e.params.toolCallId==="ok").at(-1); assert.equal(terminal.params.execution,"executed"); assert.equal(terminal.params.status,"succeeded"); assert.match(JSON.parse(out).stdout, new RegExp(root.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),"i")); } finally { await fs.rm(root,{recursive:true,force:true}); } });
