import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { GrokAcpServer, type Session } from "./server.js";
import { bindExecutionCapability } from "./executionCapability.js";
import { compileFixedInspection } from "./inspection-grammar.js";
import { prepareWriteEdit } from "./tools.js";

const profile = { status:"available" as const, platform:"win32", osFamily:"windows" as const, executable:process.env.ComSpec ?? "C:\\Windows\\System32\\cmd.exe", argvPrefix:["/d","/s","/c"] as const, displayName:"Command Prompt (cmd.exe)", dialect:"cmd" as const, pathSeparator:"\\" as const, syntax:{quoting:"",chaining:"",redirection:""} };
function call(name:string, args:Record<string,unknown>, id=name): any { return { id, type:"function", function:{name, arguments:JSON.stringify(args)} }; }
function harness(root:string, env:Record<string,string> = {}, decision:"deny"|"allow_once" = "deny") {
  const server = new GrokAcpServer(); (server as any).workspaceRoot=root; const events:any[]=[]; let permissions=0;
  (server as any).notify = (type:string, params:any) => events.push({type,params});
  (server as any).waitPermission = async () => { permissions += 1; return decision; };
  (server as any).waitEdit = async () => "reject";
  const session: Session = { id:"s", messages:[], pendingEdits:new Map(), sessionWrite:false, sessionShell:false, capability:bindExecutionCapability(profile,root,env) };
  return {server,session,events,get permissions(){return permissions;}};
}
test("Review write is staged and has no filesystem effect before acceptance", async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),"grok-review-"));try{const h=harness(root);const out=await h.server.executeTool(h.session,call("write_file",{path:"new.txt",content:"hello"}));assert.match(out,/denied|rejected/);assert.equal(await fs.stat(path.join(root,"new.txt")).then(()=>true,()=>false),false);}finally{await fs.rm(root,{recursive:true,force:true});}});
test("Trusted regular text create auto-applies and records activity provenance", async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),"grok-trusted-"));try{const h=harness(root);h.session.permissionMode="trusted_workspace";const out=await h.server.executeTool(h.session,call("write_file",{path:"new.txt",content:"hello"}));assert.match(out,/accepted/);assert.equal(await fs.readFile(path.join(root,"new.txt"),"utf8"),"hello");const terminal=h.events.find(e=>e.type==="tool_run"&&e.params.lifecycle==="terminal");assert.equal(terminal.params.execution,"executed");}finally{await fs.rm(root,{recursive:true,force:true});}});
test("structured outside-workspace target is refused before prompt or effect", async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),"grok-confine-"));try{const h=harness(root);const out=await h.server.executeTool(h.session,call("read_file",{path:"..\\outside.txt"}));assert.match(out,/outside_workspace/);assert.equal(h.permissions,0);}finally{await fs.rm(root,{recursive:true,force:true});}});
test("Bypass allows an outside regular-text write without a permission prompt", async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),"grok-bypass-root-"));const outside=await fs.mkdtemp(path.join(os.tmpdir(),"grok-bypass-outside-"));try{const h=harness(root);h.session.permissionMode="bypass_permissions";const target=path.join(outside,"outside.txt");const out=await h.server.executeTool(h.session,call("write_file",{path:target,content:"outside"}));assert.match(out,/accepted/);assert.equal(h.permissions,0);assert.equal(await fs.readFile(target,"utf8"),"outside");}finally{await fs.rm(root,{recursive:true,force:true});await fs.rm(outside,{recursive:true,force:true});}});
test("Bypass reads an outside structured target without a permission prompt", async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),"grok-bypass-read-root-"));const outside=await fs.mkdtemp(path.join(os.tmpdir(),"grok-bypass-read-outside-"));try{const target=path.join(outside,"secret.txt");await fs.writeFile(target,"outside secret");const h=harness(root);h.session.permissionMode="bypass_permissions";const out=await h.server.executeTool(h.session,call("read_file",{path:target}));assert.match(out,/outside secret/);assert.equal(h.permissions,0);}finally{await fs.rm(root,{recursive:true,force:true});await fs.rm(outside,{recursive:true,force:true});}});
test("Bypass runs a fixed inspection through a junction without a permission prompt", async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),"grok-bypass-inspect-root-"));const outside=await fs.mkdtemp(path.join(os.tmpdir(),"grok-bypass-inspect-outside-"));try{await fs.writeFile(path.join(outside,"secret.txt"),"outside secret");await fs.symlink(outside,path.join(root,"escape"),"junction");const h=harness(root,{Path:process.env.Path??"",PATHEXT:process.env.PATHEXT??".EXE"});h.session.permissionMode="bypass_permissions";const out=await h.server.executeTool(h.session,call("run_shell",{command:"rg -n secret escape/secret.txt"}));assert.match(out,/outside secret/);assert.equal(h.permissions,0);}finally{await fs.rm(root,{recursive:true,force:true});await fs.rm(outside,{recursive:true,force:true});}});
test("Review and Trusted still refuse the same outside structured and fixed targets", async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),"grok-policy-outside-root-"));const outside=await fs.mkdtemp(path.join(os.tmpdir(),"grok-policy-outside-"));try{await fs.writeFile(path.join(outside,"secret.txt"),"outside secret");await fs.symlink(outside,path.join(root,"escape"),"junction");for(const mode of ["review","trusted_workspace"] as const){const h=harness(root,{Path:process.env.Path??"",PATHEXT:process.env.PATHEXT??".EXE"});h.session.permissionMode=mode;const read=await h.server.executeTool(h.session,call("read_file",{path:path.join(outside,"secret.txt")},`read-${mode}`));assert.match(read,/outside_workspace/);const inspect=await h.server.executeTool(h.session,call("run_shell",{command:"rg -n secret escape/secret.txt"},`inspect-${mode}`));assert.match(inspect,/outside_workspace/);assert.equal(h.permissions,0);}}finally{await fs.rm(root,{recursive:true,force:true});await fs.rm(outside,{recursive:true,force:true});}});
test("write preparation fails closed when the existing target is a directory", async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),"grok-write-error-"));try{await fs.mkdir(path.join(root,"existing-dir"));await assert.rejects(()=>prepareWriteEdit(root,"write_file",{path:"existing-dir",content:"nope"},"invalid-target",true), (error:any)=>error?.code==="EISDIR"||error?.code==="EPERM");}finally{await fs.rm(root,{recursive:true,force:true});}});
test("completed tool call is idempotent and rejects argument reuse", async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),"grok-idem-"));try{const h=harness(root);await fs.writeFile(path.join(root,"a.txt"),"one");const first=await h.server.executeTool(h.session,call("read_file",{path:"a.txt"},"same"));const second=await h.server.executeTool(h.session,call("read_file",{path:"a.txt"},"same"));assert.equal(second,first);const changed=await h.server.executeTool(h.session,call("read_file",{path:"missing.txt"},"same"));assert.match(changed,/reused_with_different_arguments/);}finally{await fs.rm(root,{recursive:true,force:true});}});
test("same provider call id is independent across sessions", async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),"grok-idem-sessions-"));try{const h=harness(root);await fs.writeFile(path.join(root,"a.txt"),"one");const other={...h.session,id:"other",messages:[],pendingEdits:new Map(),sessionWrite:false,sessionShell:false};const a=await h.server.executeTool(h.session,call("read_file",{path:"a.txt"},"same"));const b=await h.server.executeTool(other as any,call("read_file",{path:"a.txt"},"same"));assert.equal(a,b);}finally{await fs.rm(root,{recursive:true,force:true});}});
test("fixed git inspection executes argv directly without permission", async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),"grok-inspect-"));try{const h=harness(root,{Path:process.env.Path??"",PATHEXT:process.env.PATHEXT??".EXE"});const out=await h.server.executeTool(h.session,call("run_shell",{command:"git status --short"}));assert.equal(h.permissions,0);assert.doesNotMatch(out,/permission/);}finally{await fs.rm(root,{recursive:true,force:true});}});
test("fixed inspection rejects absolute outside and a Windows junction operand before effect", async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),"grok-inspect-root-"));const outside=await fs.mkdtemp(path.join(os.tmpdir(),"grok-inspect-outside-"));try{const secret=path.join(outside,"secret.txt");await fs.writeFile(secret,"outside secret");const linked=path.join(root,"escape");await fs.symlink(outside,linked,"junction");const h=harness(root,{Path:process.env.Path??"",PATHEXT:process.env.PATHEXT??".EXE"});assert.equal(compileFixedInspection(`rg -n secret ${secret}`,"win32"),null);const out=await h.server.executeTool(h.session,call("run_shell",{command:"rg -n secret escape/secret.txt"}));assert.match(out,/outside_workspace/);assert.equal(h.permissions,0);assert.doesNotMatch(out,/outside secret/);}finally{await fs.rm(root,{recursive:true,force:true});await fs.rm(outside,{recursive:true,force:true});}});
test("Trusted apply_patch text auto-applies while NUL content remains gated", async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),"grok-edit-kinds-"));try{const h=harness(root);h.session.permissionMode="trusted_workspace";await fs.writeFile(path.join(root,"a.txt"),"old");const patchOut=await h.server.executeTool(h.session,call("apply_patch",{path:"a.txt",patch:"--- a/a.txt\n+++ b/a.txt\n@@ -1,1 +1,1 @@\n-old\n+new"},"p"));assert.match(patchOut,/accepted/);const binary=await h.server.executeTool(h.session,call("write_file",{path:"b.bin",content:"x\0y"},"b"));assert.match(binary,/denied|rejected/);assert.equal(await fs.stat(path.join(root,"b.bin")).then(()=>true,()=>false),false);}finally{await fs.rm(root,{recursive:true,force:true});}});
test("two production ACP servers reject overlapping stale-base edit and preserve winner", async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),"grok-overlap-prod-"));try{await fs.writeFile(path.join(root,"shared.txt"),"base");const a=harness(root),b=harness(root);a.session.permissionMode="trusted_workspace";b.session.permissionMode="trusted_workspace";const [first,second]=await Promise.all([a.server.executeTool(a.session,call("write_file",{path:"shared.txt",content:"from-a"},"a")),b.server.executeTool(b.session,call("write_file",{path:"shared.txt",content:"from-b"},"b"))]);const outputs=[first,second];assert.equal(outputs.filter(x=>/accepted/.test(x)).length,1);assert.equal(outputs.filter(x=>/edit conflict|edit_conflict/.test(x)).length,1);const final=await fs.readFile(path.join(root,"shared.txt"),"utf8");assert.ok(final==="from-a"||final==="from-b");}finally{await fs.rm(root,{recursive:true,force:true});}});
test("structured repository tools execute without permission events", async () => { const root=await fs.mkdtemp(path.join(os.tmpdir(),"grok-bnd-")); try { await fs.writeFile(path.join(root,"a.txt"),"needle"); const h=harness(root); for (const [name,args] of [["list_dir",{path:"."}],["read_file",{path:"a.txt"}],["grep",{pattern:"needle",path:"."}] ] as const) await h.server.executeTool(h.session,call(name,args)); assert.equal(h.permissions,0); assert.equal(h.events.filter(e=>e.type==="tool_run"&&e.params.lifecycle==="terminal").length,3); } finally { await fs.rm(root,{recursive:true,force:true}); } });
test("exact ls is rejected before permission and unavailable has no process", async()=>{ const root=await fs.mkdtemp(path.join(os.tmpdir(),"grok-bnd-")); try { const h=harness(root,{Path:"",PATHEXT:".EXE"}); const out=await h.server.executeTool(h.session,call("run_shell",{command:"ls"})); const terminal=h.events.find(e=>e.type==="tool_run"&&e.params.lifecycle==="terminal"); assert.equal(h.permissions,0); assert.equal(terminal.params.execution,"not_executed"); assert.equal(terminal.params.reasonCode,"leading_command_unresolved"); assert.match(out,/not_executed/); } finally { await fs.rm(root,{recursive:true,force:true}); } });
test("unavailable capability rejects without permission", async()=>{ const root=await fs.mkdtemp(path.join(os.tmpdir(),"grok-bnd-")); try { const h=harness(root); h.session.capability=bindExecutionCapability({status:"unavailable",platform:"plan9",osFamily:"unsupported",executable:null,argvPrefix:[],displayName:null,dialect:null,pathSeparator:"/",syntax:null,reasonCode:"unsupported_platform",reason:"Unsupported host platform"},root,{}); await h.server.executeTool(h.session,call("run_shell",{command:"echo ok"})); const terminal=h.events.find(e=>e.type==="tool_run"&&e.params.lifecycle==="terminal"); assert.equal(h.permissions,0); assert.equal(terminal.params.reasonCode,"unsupported_platform"); assert.equal(terminal.params.execution,"not_executed"); } finally { await fs.rm(root,{recursive:true,force:true}); } });
test("uncertain shell reaches deny permission and executed failure remains failed", async()=>{ const root=await fs.mkdtemp(path.join(os.tmpdir(),"grok-bnd-")); try { const h=harness(root,{Path:"",PATHEXT:".EXE"}); await h.server.executeTool(h.session,call("run_shell",{command:"echo %CD%"},"u")); assert.equal(h.permissions,1); const denied=h.events.filter(e=>e.type==="tool_run"&&e.params.toolCallId==="u").at(-1); assert.equal(denied.params.execution,"not_executed"); assert.equal(denied.params.status,"rejected"); h.session.sessionShell=true; const fail=await h.server.executeTool(h.session,call("run_shell",{command:"exit /b 7"},"f")); const terminal=h.events.filter(e=>e.type==="tool_run"&&e.params.toolCallId==="f").at(-1); assert.equal(terminal.params.execution,"executed"); assert.equal(terminal.params.status,"failed"); assert.match(fail,/exit_code/); } finally { await fs.rm(root,{recursive:true,force:true}); } });
test("approved compatible command asks once and uses workspace cwd", async()=>{ const root=await fs.mkdtemp(path.join(os.tmpdir(),"grok-bnd-")); try { const h=harness(root,{Path:"",PATHEXT:".EXE"},"allow_once"); const out=await h.server.executeTool(h.session,call("run_shell",{command:"echo %CD%"},"ok")); assert.equal(h.permissions,1); const terminal=h.events.filter(e=>e.type==="tool_run"&&e.params.toolCallId==="ok").at(-1); assert.equal(terminal.params.execution,"executed"); assert.equal(terminal.params.status,"succeeded"); assert.match(JSON.parse(out).stdout, new RegExp(root.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),"i")); } finally { await fs.rm(root,{recursive:true,force:true}); } });
